// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD685C6yn3DZUlDU3q8ab4gfgZcNVsvkMo',
    appId: '1:940267686745:web:470db93184631b3c745a48',
    messagingSenderId: '940267686745',
    projectId: 'translation-vendor',
    authDomain: 'translation-vendor.firebaseapp.com',
    storageBucket: 'translation-vendor.appspot.com',
    measurementId: 'G-T9LWSC354B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzhw9I2jFe1WymG7M-v141xgy-J4Ylig',
    appId: '1:940267686745:android:7b1899e3ce9c9582745a48',
    messagingSenderId: '940267686745',
    projectId: 'translation-vendor',
    storageBucket: 'translation-vendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KEMcXT2LxZ8K0RAkHjLQF18b0T-lWxM',
    appId: '1:940267686745:ios:ba187d01b368c69f745a48',
    messagingSenderId: '940267686745',
    projectId: 'translation-vendor',
    storageBucket: 'translation-vendor.appspot.com',
    iosClientId: '940267686745-ffgbujn52qglmit3gnuabcmqj7tu26u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.translationVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KEMcXT2LxZ8K0RAkHjLQF18b0T-lWxM',
    appId: '1:940267686745:ios:ba187d01b368c69f745a48',
    messagingSenderId: '940267686745',
    projectId: 'translation-vendor',
    storageBucket: 'translation-vendor.appspot.com',
    iosClientId: '940267686745-ffgbujn52qglmit3gnuabcmqj7tu26u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.translationVendor',
  );
}
